---
# Collect Kubernetes cluster information for summary
- name: Initialize cluster summary variables
  set_fact:
    processed_nodes: []
    processed_system_pods: []
  delegate_to: localhost

- name: Create temporary directory for kubeconfig
  tempfile:
    state: directory
    suffix: kubeconfig
  register: temp_kubeconfig_dir
  when: global_kubeconfig is defined
  delegate_to: localhost

- name: Set temporary directory permissions
  file:
    path: "{{ temp_kubeconfig_dir.path }}"
    mode: '0700'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  when: global_kubeconfig is defined
  delegate_to: localhost

- name: Read kubeconfig content with elevated privileges
  slurp:
    src: "{{ global_kubeconfig }}"
  register: kubeconfig_content
  become: true
  when: global_kubeconfig is defined
  delegate_to: localhost

- name: Write kubeconfig to temporary location
  copy:
    content: "{{ kubeconfig_content.content | b64decode }}"
    dest: "{{ temp_kubeconfig_dir.path }}/config"
    mode: '0600'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  when: 
    - global_kubeconfig is defined
    - kubeconfig_content is defined
  delegate_to: localhost

- name: Get cluster nodes
  shell: "kubectl --kubeconfig={{ temp_kubeconfig_dir.path }}/config get nodes -o json"
  register: k8s_nodes_raw
  ignore_errors: true
  when: global_kubeconfig is defined
  delegate_to: localhost

- name: Parse nodes output
  set_fact:
    k8s_nodes: "{{ k8s_nodes_raw.stdout | from_json }}"
  when: 
    - global_kubeconfig is defined
    - k8s_nodes_raw is defined
    - k8s_nodes_raw.rc is defined
    - k8s_nodes_raw.rc == 0
  delegate_to: localhost

- name: Get system pods status
  shell: "kubectl --kubeconfig={{ temp_kubeconfig_dir.path }}/config get pods -n kube-system -o json"
  register: k8s_system_pods_raw
  ignore_errors: true
  when: global_kubeconfig is defined
  delegate_to: localhost

- name: Parse system pods output
  set_fact:
    k8s_system_pods: "{{ k8s_system_pods_raw.stdout | from_json }}"
  when: 
    - global_kubeconfig is defined
    - k8s_system_pods_raw is defined
    - k8s_system_pods_raw.rc is defined
    - k8s_system_pods_raw.rc == 0
  delegate_to: localhost

- name: Get cluster info
  shell: "kubectl --kubeconfig={{ temp_kubeconfig_dir.path }}/config cluster-info dump --output=json"
  register: k8s_cluster_info_raw
  ignore_errors: true
  when: global_kubeconfig is defined
  delegate_to: localhost

- name: Parse cluster info output
  set_fact:
    k8s_cluster_info: "{{ k8s_cluster_info_raw.stdout | from_json }}"
  when: 
    - global_kubeconfig is defined
    - k8s_cluster_info_raw is defined
    - k8s_cluster_info_raw.rc is defined
    - k8s_cluster_info_raw.rc == 0
  delegate_to: localhost

- name: Check network readiness (CNI)
  shell: "kubectl --kubeconfig={{ temp_kubeconfig_dir.path }}/config get pods -n kube-system -l k8s-app=calico-node -o json"
  register: network_pods_raw
  ignore_errors: true
  when: global_kubeconfig is defined
  delegate_to: localhost

- name: Parse network pods output
  set_fact:
    network_pods: "{{ network_pods_raw.stdout | from_json }}"
  when: 
    - global_kubeconfig is defined
    - network_pods_raw is defined
    - network_pods_raw.rc is defined
    - network_pods_raw.rc == 0
  delegate_to: localhost

- name: Check storage readiness
  shell: "kubectl --kubeconfig={{ temp_kubeconfig_dir.path }}/config get sc -o json"
  register: storage_classes_raw
  ignore_errors: true
  when: global_kubeconfig is defined
  delegate_to: localhost

- name: Parse storage classes output
  set_fact:
    storage_classes: "{{ storage_classes_raw.stdout | from_json }}"
  when: 
    - global_kubeconfig is defined
    - storage_classes_raw is defined
    - storage_classes_raw.rc is defined
    - storage_classes_raw.rc == 0
  delegate_to: localhost

- name: Process cluster nodes information
  set_fact:
    processed_nodes: "{{ processed_nodes + [node_info] }}"
  vars:
    node_info:
      name: "{{ item.metadata.name }}"
      status: "{{ item.status.conditions | selectattr('type', 'equalto', 'Ready') | map(attribute='status') | first | default('Unknown') }}"
      role: "{{ 'control-plane' if 'node-role.kubernetes.io/control-plane' in item.metadata.labels else 'worker' }}"
      version: "{{ item.status.nodeInfo.kubeletVersion | default('unknown') }}"
  loop: "{{ k8s_nodes.items | default([]) }}"
  when: 
    - k8s_nodes is defined 
    - k8s_nodes.items is defined
  delegate_to: localhost

- name: Process system pods information
  set_fact:
    processed_system_pods: "{{ processed_system_pods + [pod_info] }}"
  vars:
    pod_info:
      name: "{{ item.metadata.name }}"
      status: "{{ item.status.phase | default('Unknown') }}"
      namespace: "{{ item.metadata.namespace }}"
      ready: "{{ item.status.conditions | selectattr('type', 'equalto', 'Ready') | map(attribute='status') | first | default('False') }}"
  loop: "{{ k8s_system_pods.items | default([]) }}"
  when: 
    - k8s_system_pods is defined 
    - k8s_system_pods.items is defined
  delegate_to: localhost

- name: Determine cluster status
  set_fact:
    cluster_status: >-
      {%- if processed_nodes | length > 0 -%}
        {%- set ready_nodes = processed_nodes | selectattr('status', 'equalto', true) | list -%}
        {%- if ready_nodes | length == processed_nodes | length -%}
          healthy
        {%- elif ready_nodes | length > 0 -%}
          partially_ready
        {%- else -%}
          unhealthy
        {%- endif -%}
      {%- else -%}
        unknown
      {%- endif -%}
  delegate_to: localhost

- name: Determine network readiness
  set_fact:
    network_ready: >-
      {%- if network_pods is defined and network_pods.items is defined -%}
        {%- set running_pods = network_pods.items | selectattr('status.phase', 'equalto', 'Running') | list -%}
        {{ running_pods | length > 0 }}
      {%- else -%}
        false
      {%- endif -%}
  delegate_to: localhost

- name: Determine storage readiness
  set_fact:
    storage_ready: >-
      {%- if storage_classes is defined and storage_classes.items is defined -%}
        {{ storage_classes.items | length > 0 }}
      {%- else -%}
        false
      {%- endif -%}
  delegate_to: localhost

- name: Update Kubernetes summary data
  set_fact:
    kubernetes_summary:
      cluster_status: "{{ cluster_status }}"
      nodes: "{{ processed_nodes | default([]) }}"
      system_pods: "{{ processed_system_pods | default([]) }}"
      network_ready: "{{ network_ready | bool }}"
      storage_ready: "{{ storage_ready | bool }}"
  delegate_to: localhost

- name: Generate summary report
  include_tasks: "{{ playbook_dir }}/tasks/summary_tracker.yml"
  vars:
    generate_summary_report: true
    generate_k8s_summary_report: true
    should_save_summary: true

- name: Cleanup temporary kubeconfig directory
  file:
    path: "{{ temp_kubeconfig_dir.path }}"
    state: absent
  when: temp_kubeconfig_dir is defined
  ignore_errors: true
  delegate_to: localhost 
