---
- name: Check kubernetes deployment flag
  fail:
    msg: |
      Error: Kubernetes flag is set to true. 
      Applications cannot be installed when kubernetes_deployment.enabled is true.
      Please set kubernetes_deployment.enabled to false in user_input.yml to install applications.
  when: 
    - kubernetes_deployment is defined
    - kubernetes_deployment.enabled | bool

- name: Validate kubernetes deployment settings
  assert:
    that:
      - kubernetes_deployment is defined
      - not kubernetes_deployment.enabled
    fail_msg: |
      Error: Invalid kubernetes deployment configuration.
      - kubernetes_deployment must be defined in user_input.yml
      - kubernetes_deployment.enabled must be set to false to install applications
    success_msg: "Kubernetes deployment check passed - applications can be installed"

- name: Check if helm diff plugin is already installed
  shell: helm plugin list | grep -q "^diff"
  register: helm_diff_check
  changed_when: false
  failed_when: false
  ignore_errors: true
  tags:
    - helm
    - prerequisites

- name: Install helm diff plugin for better idempotency checks
  shell: helm plugin install https://github.com/databus23/helm-diff
  ignore_errors: true
  changed_when: false
  register: helm_diff_install
  when: helm_diff_check.rc != 0
  tags:
    - helm
    - prerequisites

- name: Debug helm diff plugin status
  debug:
    msg: >-
      {% if helm_diff_check.rc == 0 %}
      Helm diff plugin is already installed
      {% elif helm_diff_install is defined and helm_diff_install.rc == 0 %}
      Helm diff plugin installed successfully
      {% elif helm_diff_install is defined %}
      Helm diff plugin installation failed: {{ helm_diff_install.stderr | default('Unknown error') }}
      {% else %}
      Helm diff plugin check completed
      {% endif %}
  tags:
    - helm
    - prerequisites

- name: Load and display user_input.yml content
  debug:
    var: user_input
    verbosity: 1

- name: Validate required environment variables
  fail:
    msg: |
      The following required variables are not set:
      {% if not ngc_api_key %}
      - NGC_API_KEY
      {% endif %}
      {% if not ngc_docker_api_key %}
      - NGC_DOCKER_API_KEY
      {% endif %}
      {% if not avesha_docker_username %}
      - AVESHA_DOCKER_USERNAME
      {% endif %}
      {% if not avesha_docker_password %}
      - AVESHA_DOCKER_PASSWORD
      {% endif %}
      
      Please set these variables using one of:
      1. Environment variables
      2. Command line arguments (-e)
      3. Vault file (group_vars/all/vault.yml)
  when: not ngc_api_key or not ngc_docker_api_key or not avesha_docker_username or not avesha_docker_password

- name: Validate kubeconfig settings
  block:
    - name: Check if kubeconfig file exists
      stat:
        path: "{{ global_kubeconfig }}"
      register: kubeconfig_stat
      when: global_kubeconfig is defined

    - name: Fail if kubeconfig doesn't exist
      fail:
        msg: "Kubeconfig file {{ global_kubeconfig }} does not exist. Please provide a valid kubeconfig file path in user_input.yml (global_kubeconfig)."
      when: 
        - global_kubeconfig is defined
        - not kubeconfig_stat.stat.exists

    - name: Get cluster info
      kubernetes.core.k8s_cluster_info:
        kubeconfig: "{{ global_kubeconfig }}"
        context: "{{ global_kubecontext | default(omit) }}"
      register: k8s_cluster_info

    - name: Debug cluster info
      debug:
        msg: |
          Successfully connected to Kubernetes cluster:
          - API Server: {{ k8s_cluster_info.connection.host }}
          - Context: {{ global_kubecontext | default("current-context") }}
          - Server Version: {{ k8s_cluster_info.version.server.kubernetes.gitVersion }} 