---
# IPv4/IPv6 Stack Configuration - Force IPv4-only
ipv4_stack: true
ipv6_stack: false

# Bind address configuration - use private IP to avoid dual-stack issues
# This binds all components to the node's private IPv4 address
kube_apiserver_bind_address: "{{ ansible_default_ipv4.address }}"
kube_controller_manager_bind_address: "{{ ansible_default_ipv4.address }}"
kube_scheduler_bind_address: "{{ ansible_default_ipv4.address }}"
kubelet_bind_address: "{{ ansible_default_ipv4.address }}"
kube_proxy_bind_address: "{{ ansible_default_ipv4.address }}"

# Legacy configuration for backwards compatibility (if needed)
apiserver_extra_vars:
  # Advertise address uses private IP
  kube_apiserver_advertise_address: "{{ ansible_default_ipv4.address }}"
  # Add both IPs to the certificate SANs
  supplementary_addresses_in_ssl_keys: 
    - "{{ kubernetes_deployment.api_server.host }}"  # Public IP from user input
    - "{{ ansible_default_ipv4.address }}"          # Private IP from node
  # Configure the API server endpoint
  kubeadm_config_api_fqdn: "{{ kubernetes_deployment.api_server.host }}"
  # Configure loadbalancer settings from user input
  loadbalancer_apiserver:
    address: "{{ kubernetes_deployment.api_server.host }}"
    port: "{{ kubernetes_deployment.api_server.port }}"