---
# Configure API server to listen on both internal and external IPs
apiserver_extra_vars:
  # Add both internal and external IPs to bind addresses
  kube_apiserver_bind_address: "{{ ansible_default_ipv4_address }}"
  kube_apiserver_advertise_address: "{{ ansible_default_ipv4_address }}"
  # Add both IPs to the certificate SANs
  supplementary_addresses_in_ssl_keys: 
    - "{{ ansible_host }}"
    - "{{ ansible_default_ipv4_address }}"
  # Configure the API server endpoint
  kubeadm_config_api_fqdn: "{{ ansible_default_ipv4_address }}" 