---
# Configure firewall rules for Kubernetes NVIDIA runtime communication
- name: Combine all node IPs
  set_fact:
    all_node_ips: >-
      {{ 
        (kubernetes_deployment.control_plane_nodes | map(attribute='ansible_host') | list) +
        (kubernetes_deployment.worker_nodes | default([]) | map(attribute='ansible_host') | list)
      }}
  when: kubernetes_deployment.nvidia_runtime.enabled | default(false)
  tags: nvidia_ports

- name: Configure NVIDIA Container Runtime ports
  ufw:
    rule: allow
    from_ip: "{{ item.0 }}"
    port: "{{ item.1 }}"
    proto: tcp
    comment: "NVIDIA Container Runtime"
  loop: "{{ all_node_ips | product(['8080', '3476']) | list }}"
  when: kubernetes_deployment.nvidia_runtime.enabled | default(false)
  delegate_to: "{{ inventory_hostname }}"
  vars:
    ansible_ssh_private_key_file: "{{ kubernetes_deployment.ssh_key_path }}"
    ansible_user: "{{ kubernetes_deployment.default_ansible_user }}"
  environment:
    LC_ALL: C.UTF-8
    LANG: C.UTF-8
  tags: nvidia_ports

- name: Allow containerd communication
  ufw:
    rule: allow
    from_ip: "{{ item.ansible_host }}"
    port: 10250
    proto: tcp
    comment: "Containerd for NVIDIA Runtime"
  loop: "{{ kubernetes_deployment.control_plane_nodes + kubernetes_deployment.worker_nodes | default([]) }}"
  when: kubernetes_deployment.nvidia_runtime.enabled | default(false)
  delegate_to: "{{ item.ansible_host }}"
  vars:
    ansible_ssh_private_key_file: "{{ kubernetes_deployment.ssh_key_path }}"
    ansible_user: "{{ item.ansible_user | default(kubernetes_deployment.default_ansible_user) }}"
  environment:
    LC_ALL: C.UTF-8
    LANG: C.UTF-8

- name: Reload UFW
  ufw:
    state: reloaded
  when: kubernetes_deployment.nvidia_runtime.enabled | default(false)
  delegate_to: "{{ item.ansible_host }}"
  loop: "{{ kubernetes_deployment.control_plane_nodes + kubernetes_deployment.worker_nodes | default([]) }}"
  vars:
    ansible_ssh_private_key_file: "{{ kubernetes_deployment.ssh_key_path }}"
    ansible_user: "{{ item.ansible_user | default(kubernetes_deployment.default_ansible_user) }}"
  environment:
    LC_ALL: C.UTF-8
    LANG: C.UTF-8 