---
# Configure firewall rules for Kubernetes NVIDIA runtime communication
- name: Check if UFW is installed
  command: which ufw
  register: ufw_check
  ignore_errors: true
  changed_when: false
  when: kubernetes_deployment.nvidia_runtime.enabled | default(false)
  tags: nvidia_ports

- name: Set UFW availability fact
  set_fact:
    ufw_available: "{{ ufw_check.rc == 0 }}"
  when: kubernetes_deployment.nvidia_runtime.enabled | default(false)
  tags: nvidia_ports

- name: Display warning if UFW is not available
  debug:
    msg: "WARNING: UFW is not installed. Firewall configuration will be skipped. Please ensure your firewall allows the following ports: TCP 8080, 3476, and 10250 between cluster nodes."
  when: 
    - kubernetes_deployment.nvidia_runtime.enabled | default(false)
    - not ufw_available | default(false)
  tags: nvidia_ports

- name: Combine all node IPs
  set_fact:
    all_node_ips: >-
      {{ 
        (kubernetes_deployment.control_plane_nodes | map(attribute='ansible_host') | list) +
        (kubernetes_deployment.worker_nodes | default([]) | map(attribute='ansible_host') | list)
      }}
  when: 
    - kubernetes_deployment.nvidia_runtime.enabled | default(false)
    - ufw_available | default(false)
  tags: nvidia_ports

- name: Ensure required locale is available
  shell: |
    if ! locale -a | grep -q "en_US.utf8"; then
      if command -v locale-gen > /dev/null; then
        sudo locale-gen en_US.UTF-8
      elif command -v localedef > /dev/null; then
        sudo localedef -i en_US -f UTF-8 en_US.UTF-8
      fi
    fi
  args:
    executable: /bin/bash
  changed_when: false
  delegate_to: localhost
  when: kubernetes_deployment.enabled | default(false)

- name: Configure NVIDIA Container Runtime ports
  community.general.ufw:
    rule: allow
    from_ip: "{{ item[0] }}"
    to_port: "{{ item[1] }}"
    proto: tcp
  with_nested:
    - "{{ kubernetes_deployment.control_plane_nodes | map(attribute='ansible_host') | list }}"
    - ["8080", "3476"]  # NVIDIA Container Runtime ports
  when: kubernetes_deployment.enabled | default(false)
  environment:
    LANG: "en_US.UTF-8"
    LC_ALL: "en_US.UTF-8"
    LC_CTYPE: "en_US.UTF-8"
  delegate_to: localhost

- name: Allow containerd communication
  ufw:
    rule: allow
    from_ip: "{{ item.ansible_host }}"
    port: 10250
    proto: tcp
    comment: "Containerd for NVIDIA Runtime"
  loop: "{{ kubernetes_deployment.control_plane_nodes + kubernetes_deployment.worker_nodes | default([]) }}"
  when: 
    - kubernetes_deployment.nvidia_runtime.enabled | default(false)
    - ufw_available | default(false)
  delegate_to: "{{ item.ansible_host }}"
  vars:
    ansible_ssh_private_key_file: "{{ kubernetes_deployment.ssh_key_path }}"
    ansible_user: "{{ item.ansible_user | default(kubernetes_deployment.default_ansible_user) }}"
  environment:
    LC_ALL: C.UTF-8
    LANG: C.UTF-8
  tags: nvidia_ports

- name: Reload UFW
  ufw:
    state: reloaded
  when: 
    - kubernetes_deployment.nvidia_runtime.enabled | default(false)
    - ufw_available | default(false)
  delegate_to: "{{ item.ansible_host }}"
  loop: "{{ kubernetes_deployment.control_plane_nodes + kubernetes_deployment.worker_nodes | default([]) }}"
  vars:
    ansible_ssh_private_key_file: "{{ kubernetes_deployment.ssh_key_path }}"
    ansible_user: "{{ item.ansible_user | default(kubernetes_deployment.default_ansible_user) }}"
  environment:
    LC_ALL: C.UTF-8
    LANG: C.UTF-8
